before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/ddcost
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
checksum:
  name_template: "checksums.txt"
brews:
  - tap:
      owner: winebarrel
      name: homebrew-ddcost
    homepage: https://github.com/winebarrel/ddcost
    description: A tool that shows a breakdown of Datadog costs in a table.
    license: MIT
    install: |
      bin.install 'ddcost'
